version: '3.8'
services:
  jekyll:
    image: jekyll/jekyll
    ports:
      - '4000:4000'
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve
